// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { CodecTypes as MongoCodecTypes, Vector } from '@prisma/orm-mongo/adapter/codec-types';

import type {
  MongoCollection,
  MongoContractWithTypeMaps,
  MongoTypeMaps,
  RelationKeys,
} from '@prisma/orm-mongo/family-contract';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-mongo/contract/types';

export type StorageHash =
  StorageHashBase<'59599aa72327a5019c9cc733632107da6d7b44b1eb7692f53dfa239eb681a16c'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'251b3ce23f6c9f561892e7c1af9d2cc941a13d64ba1aa7226b90036b09568cc3'>;

export type CodecTypes = MongoCodecTypes;

export type FieldOutputTypes = {
  readonly __unbound__: {
    readonly Todo: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly title: CodecTypes['mongo/string@1']['output'];
      readonly description: CodecTypes['mongo/string@1']['output'];
      readonly userId: CodecTypes['mongo/objectId@1']['output'];
      readonly done: CodecTypes['mongo/bool@1']['output'] | null;
      readonly created_At: CodecTypes['mongo/date@1']['output'];
      readonly updated_At: CodecTypes['mongo/date@1']['output'];
    };
    readonly User: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly email: CodecTypes['mongo/string@1']['output'];
      readonly username: CodecTypes['mongo/string@1']['output'] | null;
      readonly name: CodecTypes['mongo/string@1']['output'] | null;
      readonly password: CodecTypes['mongo/string@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly __unbound__: {
    readonly Todo: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly title: CodecTypes['mongo/string@1']['input'];
      readonly description: CodecTypes['mongo/string@1']['input'];
      readonly userId: CodecTypes['mongo/objectId@1']['input'];
      readonly done: CodecTypes['mongo/bool@1']['input'] | null;
      readonly created_At: CodecTypes['mongo/date@1']['input'];
      readonly updated_At: CodecTypes['mongo/date@1']['input'];
    };
    readonly User: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly email: CodecTypes['mongo/string@1']['input'];
      readonly username: CodecTypes['mongo/string@1']['input'] | null;
      readonly name: CodecTypes['mongo/string@1']['input'] | null;
      readonly password: CodecTypes['mongo/string@1']['input'];
    };
  };
};

export namespace Models {
  export type unbound_User = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    email: CodecTypes['mongo/string@1']['output'];
    username: CodecTypes['mongo/string@1']['output'] | null;
    name: CodecTypes['mongo/string@1']['output'] | null;
    password: CodecTypes['mongo/string@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type unbound_Todo = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    title: CodecTypes['mongo/string@1']['output'];
    description: CodecTypes['mongo/string@1']['output'];
    userId: CodecTypes['mongo/objectId@1']['output'];
    done: CodecTypes['mongo/bool@1']['output'] | null;
    created_At: CodecTypes['mongo/date@1']['output'];
    updated_At: CodecTypes['mongo/date@1']['output'];
    user: unbound_User;
    readonly [RelationKeys]?: 'user';
  };
}

export declare const models: {
  __unbound__: {
    User: Models.unbound_User;
    Todo: Models.unbound_Todo;
  };
};

export type TypeMaps = MongoTypeMaps<CodecTypes, FieldOutputTypes, FieldInputTypes>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly __unbound__: {
        readonly id: '__unbound__';
        readonly kind: 'mongo-database';
        readonly entries: {
          readonly collection: {
            readonly todos: {
              readonly kind: 'mongo-collection';
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly title: { readonly bsonType: 'string' };
                    readonly description: { readonly bsonType: 'string' };
                    readonly userId: { readonly bsonType: 'objectId' };
                    readonly done: { readonly bsonType: readonly ['null', 'bool'] };
                    readonly created_At: { readonly bsonType: 'date' };
                    readonly updated_At: { readonly bsonType: 'date' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly [
                    '_id',
                    'created_At',
                    'description',
                    'title',
                    'updated_At',
                    'userId',
                  ];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly users: {
              readonly kind: 'mongo-collection';
              readonly indexes: readonly [
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [{ readonly field: 'email'; readonly direction: 1 }];
                  readonly unique: true;
                },
              ];
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly email: { readonly bsonType: 'string' };
                    readonly username: { readonly bsonType: readonly ['null', 'string'] };
                    readonly name: { readonly bsonType: readonly ['null', 'string'] };
                    readonly password: { readonly bsonType: 'string' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly ['_id', 'email', 'password'];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'mongo';
  readonly targetFamily: 'mongo';
  readonly roots: {
    readonly users: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'User' };
    readonly todos: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'Todo' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly __unbound__: {
        readonly models: {
          readonly Todo: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly title: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly description: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly done: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/bool@1' };
              };
              readonly created_At: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly updated_At: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
            };
            readonly relations: {
              readonly user: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'User';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
            };
            readonly storage: { readonly collection: 'todos' };
          };
          readonly User: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly username: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly name: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly password: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly collection: 'users' };
          };
        };
      };
    };
  };
  readonly capabilities: {};
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = MongoContractWithTypeMaps<ContractBase, TypeMaps>;
